fn main() {
    /*
        If you can't handle the
        error gracefully you use the panic!()
        macro
    */
    panic!("Crash and burn");
}
